# Project identification
sonar.projectKey=Kanban-task-manager-infra-dev
sonar.projectName=Kanban Task Manager Infra Dev

# Organization (for SonarCloud only — ignore if you're using local SonarQube)

# Source code
sonar.sources=.

# Encoding and language
sonar.sourceEncoding=UTF-8

# SonarQube server (optional if in env var or default config)
# sonar.host.url=http://localhost:9000

# Authentication (can also be set via environment variable SONAR_TOKEN)
sonar.login=squ_638c6418c15277d71d3fba38d29a87a4f0c003e7
