# Runtime stage
FROM eclipse-temurin:21-jre-alpine AS runtime

WORKDIR /app

# create non-root user
RUN addgroup -g 1001 -S appgroup && \
  adduser -u 1001 -S appuser -G appgroup

COPY target/kanban-task-management-0.0.1-SNAPSHOT.jar app.jar

RUN chown appuser:appgroup app.jar && chmod 644 app.jar

USER appuser

ENTRYPOINT ["java", "-jar", "app.jar"]

