name: Deploy index.html to s3

on:
  push:
    branches: [dev]
    paths:
      - "build/"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-west-1"
  LOCAL_SYNC_PATH: "build/"

jobs:
  integrate:
    name: Run tests and deploy to dev environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure angular environment
        run: |
          echo "Configuring Angular environment"

      - name: Run tests on code
        run: |
          echo "Running Tests"

      - name: Run build on code
        run: |
          echo "Running build..."

  deploy:
    name: Deploy to aws dev environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: configure aws environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync contents to s3 (dev environment)
        run: |
          aws s3 sync ${{ env.LOCAL_SYNC_PATH }} s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate Cloudfront distribution
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
